GMT netcdf support
git-svn-id: svn://localhost/trunk@772 3bdad9f7-c964-442a-868d-553b97b55ca0

diff --git a/surfit/configure b/surfit/configure
--- a/surfit/configure
+++ b/surfit/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TCLINCLUDE TCLLIB HAVE_PTHREAD_INSTALLED_TRUE HAVE_PTHREAD_INSTALLED_FALSE HAVE_ZLIB_INSTALLED_TRUE HAVE_ZLIB_INSTALLED_FALSE MAKE_FREEFLOW_TRUE MAKE_FREEFLOW_FALSE MAKE_GLOBE_TRUE MAKE_GLOBE_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TCLINCLUDE TCLLIB NETCDFINCLUDE NETCDFLIB HAVE_PTHREAD_INSTALLED_TRUE HAVE_PTHREAD_INSTALLED_FALSE HAVE_ZLIB_INSTALLED_TRUE HAVE_ZLIB_INSTALLED_FALSE MAKE_FREEFLOW_TRUE MAKE_FREEFLOW_FALSE MAKE_GLOBE_TRUE MAKE_GLOBE_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1049,6 +1049,8 @@ Optional Packages:
   --with-tcl=path         Set location of Tcl package
   --with-tclincl=path     Set location of Tcl include directory
   --with-tcllib=path      Set location of Tcl library directory
+  --with-netcdfincl=path     Set location of netcdf include directory
+  --with-netcdflib=path      Set location of netcdf library directory
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1809,7 +1811,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=surfit
- VERSION=2.0
+ VERSION=2.1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -4750,7 +4752,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4753 "configure"' > conftest.$ac_ext
+  echo '#line 4755 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5706,7 +5708,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5709:" \
+echo "$as_me:5711:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6804,11 +6806,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6807: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6809: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6811: \$? = $ac_status" >&5
+   echo "$as_me:6813: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7066,11 +7068,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7069: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7071: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7073: \$? = $ac_status" >&5
+   echo "$as_me:7075: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7128,11 +7130,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7131: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7133: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7135: \$? = $ac_status" >&5
+   echo "$as_me:7137: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8513,7 +8515,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 8516 "configure"' > conftest.$ac_ext
+    echo '#line 8518 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9384,7 +9386,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9387 "configure"
+#line 9389 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9482,7 +9484,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9485 "configure"
+#line 9487 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11730,11 +11732,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11733: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11735: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11737: \$? = $ac_status" >&5
+   echo "$as_me:11739: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11792,11 +11794,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11795: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11797: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11799: \$? = $ac_status" >&5
+   echo "$as_me:11801: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12307,7 +12309,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 12310 "configure"' > conftest.$ac_ext
+    echo '#line 12312 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -13178,7 +13180,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13181 "configure"
+#line 13183 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13276,7 +13278,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13279 "configure"
+#line 13281 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14161,11 +14163,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14164: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14166: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14168: \$? = $ac_status" >&5
+   echo "$as_me:14170: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14223,11 +14225,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14226: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14228: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14230: \$? = $ac_status" >&5
+   echo "$as_me:14232: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15588,7 +15590,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 15591 "configure"' > conftest.$ac_ext
+    echo '#line 15593 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -16361,11 +16363,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16364: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16366: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16368: \$? = $ac_status" >&5
+   echo "$as_me:16370: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16623,11 +16625,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16626: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16628: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16630: \$? = $ac_status" >&5
+   echo "$as_me:16632: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16685,11 +16687,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16688: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16690: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16692: \$? = $ac_status" >&5
+   echo "$as_me:16694: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18070,7 +18072,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 18073 "configure"' > conftest.$ac_ext
+    echo '#line 18075 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18941,7 +18943,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18944 "configure"
+#line 18946 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19039,7 +19041,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19042 "configure"
+#line 19044 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20159,6 +20161,9 @@ fi
 
 
 
+
+
+
 # check for zlib
 
 for ac_header in zlib.h
@@ -20381,7 +20386,7 @@ else
 fi
 
 
-CXXFLAGS="-O2"
+CXXFLAGS="-O3"
 
 # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
@@ -20567,7 +20572,6 @@ echo "${ECHO_T}$i" >&6
 	done
 fi
 if test -z "$TCLINCLUDE"; then
-#	TCLINCLUDE="-I/usr/local/include"
     	{ { echo "$as_me:$LINENO: error: not found. surfit requies Tcl!" >&5
 echo "$as_me: error: not found. surfit requies Tcl!" >&2;}
    { (exit 1); exit 1; }; }
@@ -20593,11 +20597,115 @@ if test -z "$TCLLIB"; then
 	{ { echo "$as_me:$LINENO: error: not found. surfit requies Tcl!" >&5
 echo "$as_me: error: not found. surfit requies Tcl!" >&2;}
    { (exit 1); exit 1; }; }
-#	TCLLIB="-L/usr/local/lib"
 fi
 else
 echo "$as_me:$LINENO: result: $TCLLIB" >&5
 echo "${ECHO_T}$TCLLIB" >&6
+fi
+
+#--------------------------------------------------------------------
+#	Try to locate the netcdf library
+#--------------------------------------------------------------------
+NETCDFINCLUDE=
+NETCDFLIB=
+NETCDF_INSTALLED=""
+
+
+# Check whether --with-netcdfincl or --without-netcdfincl was given.
+if test "${with_netcdfincl+set}" = set; then
+  withval="$with_netcdfincl"
+
+	NETCDFINCLUDE="-I$withval"
+else
+  NETCDFINCLUDE=
+fi;
+
+# Check whether --with-netcdflib or --without-netcdflib was given.
+if test "${with_netcdflib+set}" = set; then
+  withval="$with_netcdflib"
+
+	NETCDFLIB="-L$withval"
+else
+  NETCDFLIB=
+fi;
+
+echo "$as_me:$LINENO: checking for netcdf header files" >&5
+echo $ECHO_N "checking for netcdf header files... $ECHO_C" >&6
+if test -z "$NETCDFINCLUDE"; then
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <netcdf.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  NETCDFINCLUDE=""
+fi
+rm -f conftest.err conftest.$ac_ext
+if test -z "$NETCDFINCLUDE"; then
+	dirs="$prefix/include /usr/local/include /usr/local/include /usr/include /opt/local/include"
+	for i in $dirs ; do
+		if test -r $i/netcdf.h; then
+			echo "$as_me:$LINENO: result: $i" >&5
+echo "${ECHO_T}$i" >&6
+			NETCDFINCLUDE="-I$i"
+			break
+		fi
+	done
+fi
+if test -z "$NETCDFINCLUDE"; then
+    	echo "$as_me:$LINENO: result: \"not found. surfit will be compiled without GMT maps format support!\"" >&5
+echo "${ECHO_T}\"not found. surfit will be compiled without GMT maps format support!\"" >&6
+fi
+else
+        echo "$as_me:$LINENO: result: $NETCDFINCLUDE" >&5
+echo "${ECHO_T}$NETCDFINCLUDE" >&6
+fi
+
+echo "$as_me:$LINENO: checking for netcdf library" >&5
+echo $ECHO_N "checking for netcdf library... $ECHO_C" >&6
+if test -z "$NETCDFLIB"; then
+dirs="$prefix/lib /usr/local/lib /usr/lib /opt/local/lib"
+for i in $dirs ; do
+	if test -r $i/libnetcdf.a; then
+	    echo "$as_me:$LINENO: result: $i" >&5
+echo "${ECHO_T}$i" >&6
+	    NETCDFLIB="-L$i -lnetcdf"
+	    NETCDF_INSTALLED="YES"
+	    break
+	fi
+done
+if test -z "$NETCDFLIB"; then
+	echo "$as_me:$LINENO: result: \"not found. surfit will be compiled without GMT maps format support!\"" >&5
+echo "${ECHO_T}\"not found. surfit will be compiled without GMT maps format support!\"" >&6
+fi
+else
+	echo "$as_me:$LINENO: result: $NETCDFLIB" >&5
+echo "${ECHO_T}$NETCDFLIB" >&6
 fi
 
 if [ "$PTHREAD_INSTALLED" = "YES" ] ; then
@@ -20606,6 +20714,15 @@ if [ "$PTHREAD_INSTALLED" = "YES" ] ; then
 _ACEOF
 
 fi
+
+if [ "$NETCDF_INSTALLED" = "YES" ] ; then
+	cat >>confdefs.h <<\_ACEOF
+#define HAVE_NETCDF 1
+_ACEOF
+
+fi
+
+
 
 
 
@@ -21401,6 +21518,8 @@ s,@LIBTOOL@,$LIBTOOL,;t t
 s,@LIBTOOL_DEPS@,$LIBTOOL_DEPS,;t t
 s,@TCLINCLUDE@,$TCLINCLUDE,;t t
 s,@TCLLIB@,$TCLLIB,;t t
+s,@NETCDFINCLUDE@,$NETCDFINCLUDE,;t t
+s,@NETCDFLIB@,$NETCDFLIB,;t t
 s,@HAVE_PTHREAD_INSTALLED_TRUE@,$HAVE_PTHREAD_INSTALLED_TRUE,;t t
 s,@HAVE_PTHREAD_INSTALLED_FALSE@,$HAVE_PTHREAD_INSTALLED_FALSE,;t t
 s,@HAVE_ZLIB_INSTALLED_TRUE@,$HAVE_ZLIB_INSTALLED_TRUE,;t t
