no message
git-svn-id: svn://localhost/trunk@828 3bdad9f7-c964-442a-868d-553b97b55ca0

diff --git a/surfit/configure b/surfit/configure
--- a/surfit/configure
+++ b/surfit/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TCLINCLUDE TCLLIB NETCDFINCLUDE NETCDFLIB HAVE_PTHREAD_INSTALLED_TRUE HAVE_PTHREAD_INSTALLED_FALSE HAVE_ZLIB_INSTALLED_TRUE HAVE_ZLIB_INSTALLED_FALSE HAVE_JPEG_INSTALLED_TRUE HAVE_JPEG_INSTALLED_FALSE MAKE_FREEFLOW_TRUE MAKE_FREEFLOW_FALSE MAKE_GLOBE_TRUE MAKE_GLOBE_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TCLINCLUDE TCLLIB NETCDFINCLUDE NETCDFLIB HAVE_PTHREAD_INSTALLED_TRUE HAVE_PTHREAD_INSTALLED_FALSE HAVE_ZLIB_INSTALLED_TRUE HAVE_ZLIB_INSTALLED_FALSE HAVE_JPEG_INSTALLED_TRUE HAVE_JPEG_INSTALLED_FALSE MAKE_SURFIT_IO_TRUE MAKE_SURFIT_IO_FALSE MAKE_FREEFLOW_TRUE MAKE_FREEFLOW_FALSE MAKE_GLOBE_TRUE MAKE_GLOBE_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1034,6 +1034,7 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-debug          compiling with debugging info
   --enable-pthread        compiling with threads support
+  --enable-surfit_io       turn on surfit_io compilation default=yes
   --enable-freeflow       turn on freeflow compilation default=yes
   --enable-globe          turn on globe compilation default=yes
 
@@ -4752,7 +4753,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4755 "configure"' > conftest.$ac_ext
+  echo '#line 4756 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5708,7 +5709,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5711:" \
+echo "$as_me:5712:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6806,11 +6807,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6809: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6810: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6813: \$? = $ac_status" >&5
+   echo "$as_me:6814: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7068,11 +7069,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7071: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7072: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7075: \$? = $ac_status" >&5
+   echo "$as_me:7076: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7130,11 +7131,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7133: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7134: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7137: \$? = $ac_status" >&5
+   echo "$as_me:7138: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8515,7 +8516,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 8518 "configure"' > conftest.$ac_ext
+    echo '#line 8519 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9386,7 +9387,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9389 "configure"
+#line 9390 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9484,7 +9485,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9487 "configure"
+#line 9488 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11732,11 +11733,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11735: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11736: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11739: \$? = $ac_status" >&5
+   echo "$as_me:11740: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11794,11 +11795,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11797: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11798: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11801: \$? = $ac_status" >&5
+   echo "$as_me:11802: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12309,7 +12310,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 12312 "configure"' > conftest.$ac_ext
+    echo '#line 12313 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -13180,7 +13181,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13183 "configure"
+#line 13184 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13278,7 +13279,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13281 "configure"
+#line 13282 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14163,11 +14164,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14166: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14167: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14170: \$? = $ac_status" >&5
+   echo "$as_me:14171: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14225,11 +14226,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14228: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14229: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14232: \$? = $ac_status" >&5
+   echo "$as_me:14233: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15590,7 +15591,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 15593 "configure"' > conftest.$ac_ext
+    echo '#line 15594 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -16363,11 +16364,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16366: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16367: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16370: \$? = $ac_status" >&5
+   echo "$as_me:16371: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16625,11 +16626,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16628: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16629: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16632: \$? = $ac_status" >&5
+   echo "$as_me:16633: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16687,11 +16688,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16690: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16691: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16694: \$? = $ac_status" >&5
+   echo "$as_me:16695: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18072,7 +18073,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 18075 "configure"' > conftest.$ac_ext
+    echo '#line 18076 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18943,7 +18944,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18946 "configure"
+#line 18947 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19041,7 +19042,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19044 "configure"
+#line 19045 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20630,6 +20631,11 @@ if test "${enable_pthread+set}" = set; then
 	fi
 fi;
 
+# Check whether --enable-surfit_io or --disable-surfit_io was given.
+if test "${enable_surfit_io+set}" = set; then
+  enableval="$enable_surfit_io"
+
+fi;
 # Check whether --enable-freeflow or --disable-freeflow was given.
 if test "${enable_freeflow+set}" = set; then
   enableval="$enable_freeflow"
@@ -20640,6 +20646,12 @@ if test "${enable_globe+set}" = set; then
   enableval="$enable_globe"
 
 fi;
+
+if test x$enable_surfit_io != xno; then
+   BUILD_SURFIT_IO="YES"
+else
+   BUILD_SURFIT_IO=""
+fi
 
 if test x$enable_freeflow != xno; then
    BUILD_FREEFLOW="YES"
@@ -20987,6 +20999,16 @@ fi
 
 
 
+if test "x$BUILD_SURFIT_IO" != "x"; then
+  MAKE_SURFIT_IO_TRUE=
+  MAKE_SURFIT_IO_FALSE='#'
+else
+  MAKE_SURFIT_IO_TRUE='#'
+  MAKE_SURFIT_IO_FALSE=
+fi
+
+
+
 if test "x$BUILD_FREEFLOW" != "x"; then
   MAKE_FREEFLOW_TRUE=
   MAKE_FREEFLOW_FALSE='#'
@@ -21137,6 +21159,13 @@ if test -z "${HAVE_JPEG_INSTALLED_TRUE}" && test -z "${HAVE_JPEG_INSTALLED_FALSE
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_JPEG_INSTALLED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_JPEG_INSTALLED\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${MAKE_SURFIT_IO_TRUE}" && test -z "${MAKE_SURFIT_IO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MAKE_SURFIT_IO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MAKE_SURFIT_IO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -21768,6 +21797,8 @@ s,@HAVE_ZLIB_INSTALLED_TRUE@,$HAVE_ZLIB_INSTALLED_TRUE,;t t
 s,@HAVE_ZLIB_INSTALLED_FALSE@,$HAVE_ZLIB_INSTALLED_FALSE,;t t
 s,@HAVE_JPEG_INSTALLED_TRUE@,$HAVE_JPEG_INSTALLED_TRUE,;t t
 s,@HAVE_JPEG_INSTALLED_FALSE@,$HAVE_JPEG_INSTALLED_FALSE,;t t
+s,@MAKE_SURFIT_IO_TRUE@,$MAKE_SURFIT_IO_TRUE,;t t
+s,@MAKE_SURFIT_IO_FALSE@,$MAKE_SURFIT_IO_FALSE,;t t
 s,@MAKE_FREEFLOW_TRUE@,$MAKE_FREEFLOW_TRUE,;t t
 s,@MAKE_FREEFLOW_FALSE@,$MAKE_FREEFLOW_FALSE,;t t
 s,@MAKE_GLOBE_TRUE@,$MAKE_GLOBE_TRUE,;t t
